language: python
python:
    - "2.7"

install:
    - pip install virtualenv
    - virtualenv flask
    - source flask/bin/activate
    - pip install -r requirements.txt
    - ./install.sh

script:
    - pytest
